# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FlexStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FlexStudy
pod 'GoogleMaps'
pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'FirebaseAuth'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'

  target 'FlexStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FlexStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
